name:                instapaper-sender
version:             0.1.0.0
synopsis:            Basic HTTP gateway to save articles to Instapaper
description:         Please see README.md
homepage:            https://github.com/spinda/instapaper-sender#readme
license:             AGPL-3.0
license-file:        COPYING
author:              Michael Smith
maintainer:          michael@spinda.net
copyright:           2017 Michael Smith
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 0.11.3.0 && < 1.2
  - bytestring >= 0.10.8.1 && < 0.11
  - data-default-class >= 0.1.2.0 && < 0.2
  - HaskellNet >= 0.5.1 && < 0.6
  - HaskellNet-SSL >= 0.3.3.0 && < 0.4
  - http-types >= 0.9.1 && < 0.10
  - network >= 2.6.3.1 && < 2.7
  - scotty >= 0.11.0 && < 0.12
  - text >= 1.2.2.1 && < 1.3
  - wai >= 3.2.1.1 && < 3.3
  - wai-extra >= 3.0.19.1 && < 3.1

executables:
  instapaper-sender:
    source-dirs:      src
    main:             Main.hs
